trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: gogit

steps:
  - checkout: self
  - script: |
      git config --global user.email "sedp-ci@shell.com"
      git config --global user.name "Azure Pipeline"
      git config --global url."https://test:${GIT_READ_TOKEN}@dev.azure.com/sede-ds-adp/Platform%20-%20General/_git/sedp-tf-az-tagging".insteadOf https://sede-ds-adp.visualstudio.com/Platform%20-%20General/_git/sedp-tf-az-tagging
  - script: |
      mv versions.tf  .

  - task: a4789e5d-f6e8-431f-add9-379d640a883c@0
    inputs:
      terraformVersion: "0.14.8"

  - script: |
      cp .provider/* .
      terraform init
    displayName: Terraform Init

  - script: |
      terraform validate
    displayName: Terraform Validate
