trigger:
  - test2
  
pool:
  vmImage: "ubuntu-latest"

variables:
  - name: GO111MODULE
    value: on
  - name: CGO_ENABLED
    value: "0"
  - name: GOROOT
    value: "/opt/hostedtoolcache/go/1.14.6/x64"
  - name: GOPRIVATE
    value: "dev.azure.com/sede-ds-adp"
  - group: gogit
  - group: stratos_acr
  - name: REGISTRY
    value: stratosprd.azurecr.io/kubeform

resources:
  repositories:
    - repository: kfc
      type: git
      name: Platform - General/kfc
    - repository: kfc
      type: git
      name: Platform - General/kfc
    - repository: kfc
      type: git
      name: Platform - General/kfc