trigger:
  branches:
    include:
      - navexm
    exclude:
      - master
  paths:
    include:
      - module-sources.json

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: GO111MODULE
    value: on
  - name: CGO_ENABLED
    value: "0"
  - name: GOROOT
    value: "/opt/hostedtoolcache/go/1.14.6/x64"
  - name: GOPRIVATE
    value: "dev.azure.com/sede-ds-adp"
  - group: gogit
  
resources:
  repositories:
    - repository: kubeform
      type: git
      name: Platform - General/kubeform

steps:
  - checkout: self
    displayName: Checkout sedp-tf-az-fnapp
    persistCredentials: true
  - checkout: kubeform
    displayName: Checkout kubeform