trigger:
  - test1

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: GO111MODULE
    value: on
  - name: CGO_ENABLED
    value: "0"
  - name: GOROOT
    value: "/opt/hostedtoolcache/go/1.14.6/x64"
  - name: GOPRIVATE
    value: "dev.azure.com/sede-ds-adp"
  - group: gogit

resources:
  repositories:
    - repository: kubeform
      type: git
      name: Platform - General/kubeform
    
    - repository: kfc
      type: git
      name: Platform - General/kfc
      
steps:
  - checkout: self
    displayName: Checkout sedp-tf-az-fnapp
    persistCredentials: true
  - checkout: kubeform
    displayName: Checkout kubeform
  - checkout: kfc
    displayName: Checkout kfc
    persistCredentials: true
  
  - script: |
      mv .provider/versions.tf  .

  - task: a4789e5d-f6e8-431f-add9-379d640a883c@0
    inputs:
      terraformVersion: "0.12.26"

  - script: |
      cp .provider/* .
      terraform init
    displayName: Terraform Init

  - script: |
      terraform validate
    displayName: Terraform Validate