trigger:
  - navexm
  
pool:
  vmImage: "ubuntu-latest"

variables:
  - name: GO111MODULE
    value: on
  - name: CGO_ENABLED
    value: "0"
  - name: GOROOT
    value: "/opt/hostedtoolcache/go/1.14.6/x64"
  - name: GOPRIVATE
    value: "dev.azure.com/sede-ds-adp"
  - group: gogit
  - group: stratos_acr
  - name: REGISTRY
    value: stratosprd.azurecr.io/kubeform

resources:
  repositories:
    - repository: kubeform
      type: git
      name: Platform - General/kubeform
    
steps:
  - checkout: self
  - script: |
      git config --global user.email "sedp-ci@shell.com"
      git config --global user.name "Azure Pipeline"
      git config --global url."https://test:${GIT_READ_TOKEN}@dev.azure.com/sede-ds-adp/Platform%20-%20General/_git/sedp-tf-az-tagging".insteadOf https://sede-ds-adp.visualstudio.com/Platform%20-%20General/_git/sedp-tf-az-tagging
  - script: |
      mv .provider/versions.tf  .

  - task: a4789e5d-f6e8-431f-add9-379d640a883c@0
    inputs:
      terraformVersion: "0.12.26"

  - script: |
      cp .provider/* .
      terraform init
    displayName: Terraform Init

  - script: |
      terraform validate
    displayName: Terraform Validate
  - task: KubectlInstaller@0
    inputs:
      kubectlVersion: "1.18.3"
  - task: GoTool@0
    inputs:
      version: "1.14.6"
  - script: |
      git config --global user.email "sedp-ci@shell.com"
      git config --global user.name "Azure Pipeline"
      git config --global url."https://test:${GIT_READ_TOKEN}@dev.azure.com/sede-ds-adp/Platform%20-%20General/_git/sedp-tf-az-tagging".insteadOf https://sede-ds-adp.visualstudio.com/Platform%20-%20General/_git/sedp-tf-az-tagging
     
  
